"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class observ_t(object):
    __slots__ = ["base_lin_vel", "base_ang_vel", "gravity", "commands", "dof_pos", "dof_vel", "action", "quaternion"]

    __typenames__ = ["double", "double", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [[3], [3], [3], [3], [12], [12], [12], [4]]

    def __init__(self):
        self.base_lin_vel = [ 0.0 for dim0 in range(3) ]
        self.base_ang_vel = [ 0.0 for dim0 in range(3) ]
        self.gravity = [ 0.0 for dim0 in range(3) ]
        self.commands = [ 0.0 for dim0 in range(3) ]
        self.dof_pos = [ 0.0 for dim0 in range(12) ]
        self.dof_vel = [ 0.0 for dim0 in range(12) ]
        self.action = [ 0.0 for dim0 in range(12) ]
        self.quaternion = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(observ_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.base_lin_vel[:3]))
        buf.write(struct.pack('>3d', *self.base_ang_vel[:3]))
        buf.write(struct.pack('>3d', *self.gravity[:3]))
        buf.write(struct.pack('>3d', *self.commands[:3]))
        buf.write(struct.pack('>12d', *self.dof_pos[:12]))
        buf.write(struct.pack('>12d', *self.dof_vel[:12]))
        buf.write(struct.pack('>12d', *self.action[:12]))
        buf.write(struct.pack('>4d', *self.quaternion[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != observ_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return observ_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = observ_t()
        self.base_lin_vel = struct.unpack('>3d', buf.read(24))
        self.base_ang_vel = struct.unpack('>3d', buf.read(24))
        self.gravity = struct.unpack('>3d', buf.read(24))
        self.commands = struct.unpack('>3d', buf.read(24))
        self.dof_pos = struct.unpack('>12d', buf.read(96))
        self.dof_vel = struct.unpack('>12d', buf.read(96))
        self.action = struct.unpack('>12d', buf.read(96))
        self.quaternion = struct.unpack('>4d', buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if observ_t in parents: return 0
        tmphash = (0x598ffe4f8c8829c0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if observ_t._packed_fingerprint is None:
            observ_t._packed_fingerprint = struct.pack(">Q", observ_t._get_hash_recursive([]))
        return observ_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", observ_t._get_packed_fingerprint())[0]

